config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # HOME
  root 'home#index'
  get '/home',          to: 'home#index'

  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :tasks, dependent: :destroy

  has_rich_text :description

  validates_presence_of :title
  validates_presence_of :description
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  has_rich_text :description

  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :deadline
  validates :completed, inclusion: [true, false]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @user = current_user
    @categories = @user.categories.all.with_rich_text_description.order('created_at DESC')
  end

  def show
    @tasks = @category.tasks.all.with_rich_text_description.order('deadline ASC')

    @tasks_past_due = @tasks.where('deadline <= ?', Date.tomorrow)
    @tasks_others = @tasks.where('deadline > ?', Date.tomorrow)

    @total_tasks = @tasks.count
    @completed_tasks = @tasks.where(completed: true).count
    @percent_complete = (@completed_tasks.to_f / @total_tasks * 100).round(2)
  end

  def new
    @category = Category.new
  end

  def create
    @user = current_user
    @category = @user.categories.build(category_params)
    @category.save!

    if @category.valid?
      flash[:notice] = 'Category successfully created!'
      redirect_to categories_path
    else
      flash[:alert] = 'Something went wrong...'
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category successfully edited!'
      redirect_to categories_path
    else
      flash[:alert] = 'Something went wrong...'
      render :new
    end
  end

  def destroy
    @category.destroy

    flash[:notice] = 'Category successfully deleted!'
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to categories_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category, only: %i[show new create edit update destroy]

  def index; end

  def show
    @task = @category.tasks.find(params[:id])
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      flash.notice = 'Success: Task added!'
      redirect_to category_path(@category)
    else
      flash.alert = 'Failed: Error in adding task!'
    end
  end

  def edit
    @task = @category.tasks.find(params[:id])
  end

  def update
    @task = @category.tasks.find(params[:id])

    if @task.update(task_params)
      flash.notice = 'Success: Task updated!'
      redirect_to category_path(@category)
    else
      flash.alert = 'Failed: Error in updating task!'
    end
  end

  def destroy
    @task = @category.tasks.find(params[:id])
    @task.destroy

    flash[:notice] = 'Task successfully deleted!'
    redirect_to category_path(@category)
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :completed, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml.erb' %>">
<meta name="theme-color" content="#ffffff">

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <div>
    <%= f.label :title, class: 'cat-label' %>
    <br>
    <%= f.text_field :title, class: 'cat-input' %>
  </div>
  <div>
    <%= f.label :description, class: 'cat-label' %>
    <%= f.rich_text_area :description %>
  </div>
  <div>
    <%= f.submit class: "catBtn edit-create-btn" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="cat-form-container">
  <h2>Edit Category</h2>
  
  <%= render "form", category: @category %>
</div>

app/views/categories/index.html.erb
<% if @categories.count.zero? %>
  <p class="intro-par">Add a new Category for your tasks to start planning!</p>
<% end %>

<%= link_to new_category_path(@category) do %>
  <%= content_tag :button, "Add Category +", class: "catBtn create-btn" %>
<% end %>

<div class="container">
  <div class="row row-cols-1 row-cols-md-4 row-cols-sm-2 align-items-stretch g-4 py-5">
    <% @categories.each do |category| %>
      <div class="myCol">
        <div class="myCard">
          <div class="cardHead"><%= link_to category.title, category , class: "cardHeadClr" %></div>
          <div class="cardBody"><%= category.description %></div>
          <div class="cardFooter">
            <%= link_to ' ≡ ', category_path(category), class: 'card-icon', title: 'See More' %>
            | 
            <%= link_to ' ✎ ', edit_category_path(category), class: 'card-icon', title: 'Edit' %> 
            |
            <%= link_to ' ✘ ', category_path(category), method: :delete, 
                data: {confirm: "Are you sure you want to delete this Category?"}, 
                class: 'card-icon', title: 'Delete Category' %> 
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="cat-form-container">
  <h2>Create New Category</h2>
  
  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div class="catBody">
  <div class="catHead">
    <h1 class="catTitle"><%= @category.title %></h1>
    <div class="catDes"><%= @category.description %></div>
    <div class="catActions">
        <%= link_to edit_category_path(@category) do %>
          <%= content_tag :button, "Edit &#9998;".html_safe, class: "catBtn" %>
        <% end %>
        <%= link_to category_path, method: :delete, data: {confirm: "Are you sure you want to delete this Category?"} do %>
          <%= content_tag :button, "Delete &#10008".html_safe, class: "catBtn" %>
        <% end %>
    </div>
  </div>
  <div class="catMid">
    <div><%= render "tasks/past_due" %></div>
    <div><%= render "tasks/others" %></div>
    <%= link_to 'Add Task +', new_category_task_path(@category), class: "addTask" %>
  </div>

  <% if @tasks.count != 0 %>
    <div class="progressCon">
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: <%= @percent_complete %>%;" aria-valuenow="<%= @percent_complete %>" aria-valuemin="0" aria-valuemax="100"><%= @percent_complete %>%</div>
      </div>
      <div class="progressDes"><%= @completed_tasks %> of <%= @total_tasks %> tasks accomplished!</div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="body">
  <div class="logo">
  <%= image_tag("ourjournalIcon.png", size: "450x280", alt: "facebook") %>
  </div>
  <div class="about">
    <span class="bigFont"><strong>OurJournal</strong> is an easy, free, and flexible way</span><br>
    <span class="medFont">to manage your tasks and organize anything.</span><br>
    <span class="medFont">It is trusted by millions of people from all over the globe.</span>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="jumbotron text-center">
  <div class="footerTop">
    <a href="#" style="color: white"><div class="footerTopEach">What we do</div></a>
    <a href="#" style="color: white"><div class="footerTopEach">Our work</div></a>
    <a href="#" style="color: white"><div class="footerTopEach">Company</div></a>
    <a href="#" style="color: white"><div class="footerTopEach">Contact</div></a>
  </div>
  <div class="footerMidOne">
    <a href="#"><%= image_tag("facebookIcon.png", size: "50x40", alt: "facebook") %></a>
    <a href="#"><%= image_tag("twitterIcon.png", size: "35x35", alt: "twitter") %></a>
    <a href="#"><%= image_tag("linkedinIcon.png", size: "35x35", alt: "linkedin") %></a>
    <a href="#"><%= image_tag("instagramIcon.png", size: "35x35", alt: "instagram") %></a>
  </div>
  <div class="footerMidTwo">
    <div>1 Hacker Way in Menlo Park, CA 94025</div>
    <div>678.874.5800</div>
    <div class="email">hello@myjournal.com</div>
  </div>
  <div class="footerBot">Ruby Project by: <a href="https://github.com/theIanMilan" target="_blank">theIanMilan</a> and <a href="https://github.com/JansonSiy" target="_blank">Janson Siy</a>. All rights reserved.</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="links">
    <div><%= link_to 'Home', home_path, class: "link" %></div>
    <div><a class="link" href="#">Services</a></div>
    <div><a class="link" href="#">About</a></div>
    <div><a class="link" href="#">Membership</a></div>
  </div>

    <% if user_signed_in? %>
      <div class="signedInCon">
        <div>Logged in as <strong><%= current_user.email %></strong></div>
        <div>
          <%= link_to 'Edit profile', edit_user_registration_path, class: "link" %> |
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "link" %>
        </div>
      </div>
    <% else %>
      <div class="loginCon">
        <%= link_to "<button class='button'>Login</button>".html_safe, new_user_session_path %></button>
        <%= link_to "<button class='button'>Sign-up</button>".html_safe, new_user_registration_path %></button>
      </div>
    <% end %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Our Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'application/favicon' %>

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora&family=Poppins:wght@100;300;400;700&display=swap" rel="stylesheet"> 
  </head>

  <body>
    <%# Flash %>
    <% unless flash.empty? %>
      <div id='flash'>
        <script type="text/javascript">
            <% flash.each do |f| %>
              <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
              toastr['<%= type %>']('<%= f[1] %>', '', { closeButton: true, progressBar: true, newestOnTop: false, positionClass: 'toast-bottom-right' });    
            <% end %>
        </script>
      </div>
    <% end %>

    <div id="page-container">

      <div id="content-wrap">
      <%= render "layouts/header" %>
      <section class="content"><%= yield %></section>
      </div>

      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [ @category, @task ], html: {class: "myForm"} do |form| %>
  
  <div><%= form.label :title, :class => "subLabel" %>:</div>
  <%= form.text_field :title, placeholder:'task title...', :class => "subInput" %>

  <div><%= form.label :description, :class => "subLabel" %>:</div>
  <%= form.rich_text_area :description, placeholder:'description...', :class => "subInput",
                        size: '50x3' %>

  <div><%= form.label :deadline, :class => "subLabel" %>:</div>
  <%= form.text_field :deadline, placeholder:'select date and time...',
                          class: 'datepicker subInput' %>
  
  <%= javascript_pack_tag 'flatpickr' %>

  <div class="accomplished">
    <%= form.label :completed, "Task finished?" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit 'Submit', class: 'submitBtn' %>
  </div>

  <div class="reminder">
    Please fill in all the details required*
  </div>
<% end %>

app/views/tasks/_others.html.erb
<%# Renders only if there are tasks due today %>
<% if @tasks_others.count != 0 %>
    <div class="tableHeader"> Pending Tasks </div>
    <table>
    <thead>
        <tr>
            <th>Task</th>
            <th>Deadline</th>
            <th>Status</th>
            <th>Actions</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @tasks_others.each do |task| %>
        <tr>
            <td><%= task.title %></td>
            <td><%= task.deadline.strftime('%B %d, %Y %H:%M %p') %></td>
            <td><% if task.completed %>
                    <div class="text-success">Accomplished</div>
                <% else %>
                    <div class="text-secondary">Pending</div>
                <% end %>
            </td>
            <td><%= link_to 'See More', category_task_path(@category, task), class: "tableLink" %></td>
            <td><%= link_to 'Edit', edit_category_task_path(@category, task), class: "tableLink" %></td>
            <td><%= link_to 'Delete Task', category_task_path(@category, task),
                method: :delete,
                data: { confirm: "Are you sure?"}, 
                class: "tableLink" %>
            </td>
        </tr>
        <% end %>
    </tbody>
    </table>
<% end %>

app/views/tasks/_past_due.html.erb
<%# Renders only if there are tasks due today/ past due %>
<% if @tasks_past_due.count != 0 %>
    <div class="tableHeader"> Past Due / Due Today </div>
    <table>
    <thead>
        <tr>
            <th>Task</th>
            <th>Deadline</th>
            <th>Status</th>
            <th>Actions</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @tasks_past_due.each do |task| %>
        <tr>
            <td><%= task.title %></td>
            <td><%= task.deadline.strftime('%B %d, %Y %H:%M %p') %></td>
            <td><% if task.completed %>
                    <div class="text-success">Accomplished</div>
                <% else %>
                    <div class="text-danger">Pending</div>
                <% end %>
            </td>
            <td><%= link_to 'See More', category_task_path(@category, task), class: "tableLink" %></td>
            <td><%= link_to 'Edit', edit_category_task_path(@category, task), class: "tableLink" %></td>
            <td><%= link_to 'Delete Task', category_task_path(@category, task),
                method: :delete,
                data: { confirm: "Are you sure?"}, 
                class: "tableLink" %>
            </td>
        </tr>
        <% end %>
    </tbody>
    </table>
<% end %>

app/views/tasks/edit.html.erb
<div class="newTaskCon">
  <div class ="newTaskTitleCon">
    <span class="titleAdd">Edit</span>
    <span class="titleNew">Your</span>
    <span class="titleTask">Task</span>
  </div>
  <div class ="newTaskFormCon">
     <%= render "form", category: @category, task: @task %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="newTaskCon">
  <div class ="newTaskTitleCon">
    <span class="titleAdd">Add</span>
    <span class="titleNew">New</span>
    <span class="titleTask">Task</span>
  </div>
  <div class ="newTaskFormCon">
     <%= render "form", category: @category, task: @task %>
  </div>
</div>

app/views/tasks/show.html.erb
<h1>Task Title</h1>
<div><%= @category.title %></div>
<br>
<h1>Notes</h1>
<div><%= @task.description %></div>

<h1>Status</h1>
<% if @task.completed %>
  <p class="text-success">Accomplished</p>
<% else %>
  <% if @task.deadline.to_date == Date.today %>
    <p class="text-danger">Pending</p>
  <% else %>
    <p class="text-secondary">Pending</p>
  <% end %>
<% end %>

<h1>Due</h1>
 <%= @task.deadline.strftime('%B %d, %Y %H:%M %p') %>

<%= link_to edit_category_task_path(@category, @task) do %>
  <%= content_tag :button, "Edit", class: "edit-btn" %>
<% end %>

<%= link_to category_task_path(@category, @task), method: :delete, data: {confirm: "Are you sure?"} do %>
  <%= content_tag :button, "Delete", class: "delete-btn" %>
<% end %>